macro (begin_project)

get_filename_component(PROJECT_NAME ${CMAKE_CURRENT_SOURCE_DIR} NAME)
string(REPLACE " " "_" PROJECT_NAME ${PROJECT_NAME})
project(${PROJECT_NAME} VERSION 0.1 LANGUAGES CXX)

string(TOUPPER ${PROJECT_NAME} _CURRENT_PROJECT_NAME_TO_UPPER)
cmake_language(EVAL CODE "
    set(${_CURRENT_PROJECT_NAME_TO_UPPER}_BINARY_DIR ${CMAKE_CURRENT_BINARY_DIR})
")

if (EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/models)
    cmake_language(EVAL CODE "
        set(${_CURRENT_PROJECT_NAME_TO_UPPER}_MODELS_DIR ${CMAKE_CURRENT_SOURCE_DIR}/models)
    ")
endif()

if (EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/textures)
    cmake_language(EVAL CODE "
        set(${_CURRENT_PROJECT_NAME_TO_UPPER}_TEXTURES_DIR ${CMAKE_CURRENT_SOURCE_DIR}/textures)
    ")
endif()


if (EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/shaders)
    cmake_language(EVAL CODE "
        set(${_CURRENT_PROJECT_NAME_TO_UPPER}_SHADERS_DIR ${CMAKE_CURRENT_SOURCE_DIR}/shaders)
    ")

    file(GLOB_RECURSE "${_CURRENT_PROJECT_NAME_TO_UPPER}_SHADER_SOURCES" ABSOLUTE "${${_CURRENT_PROJECT_NAME_TO_UPPER}_SHADERS_DIR}/*")
endif()

endmacro(begin_project)

macro (end_project)

if (DEFINED "${_CURRENT_PROJECT_NAME_TO_UPPER}_MODELS_DIR")
	message(${PROJECT_NAME} " models exist")
	add_custom_command(TARGET ${PROJECT_NAME}
		POST_BUILD
		COMMAND "${CMAKE_COMMAND}" -E create_symlink "${${_CURRENT_PROJECT_NAME_TO_UPPER}_MODELS_DIR}" "$<TARGET_FILE_DIR:${PROJECT_NAME}>/models")
endif()

if (DEFINED "${_CURRENT_PROJECT_NAME_TO_UPPER}_TEXTURES_DIR")
	message(${PROJECT_NAME} " textures exist")
	add_custom_command(TARGET ${PROJECT_NAME}
		POST_BUILD
		COMMAND "${CMAKE_COMMAND}" -E create_symlink "${${_CURRENT_PROJECT_NAME_TO_UPPER}_TEXTURES_DIR}"  "$<TARGET_FILE_DIR:${PROJECT_NAME}>/textures")
endif()

if (DEFINED "${_CURRENT_PROJECT_NAME_TO_UPPER}_SHADER_SOURCES")
	message(${PROJECT_NAME} " shaders exist")
	add_custom_command(TARGET ${PROJECT_NAME}
		POST_BUILD
		COMMAND "${CMAKE_COMMAND}" -E create_symlink "${CMAKE_CURRENT_BINARY_DIR}/shaders"  "$<TARGET_FILE_DIR:${PROJECT_NAME}>/shaders")

	include(${CMAKE_SOURCE_DIR}/cmake_utils/glslc.cmake)
	generate_glslc_script(PROJECT_DIR ${CMAKE_CURRENT_BINARY_DIR} SHADER_PATHS "${${_CURRENT_PROJECT_NAME_TO_UPPER}_SHADER_SOURCES}")
	install (DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/shaders DESTINATION ${PROJECT_NAME})
endif()

install (TARGETS ${PROJECT_NAME} DESTINATION ${PROJECT_NAME})

set_target_properties(${PROJECT_NAME} PROPERTIES
	ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_BUILD_TYPE}/"
	LIBRARY_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_BUILD_TYPE}/"
	RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_BUILD_TYPE}/")

endmacro (end_project)
