#ifndef GAPI_FWD_HPP
#define GAPI_FWD_HPP

#include "include/gapi.hpp"

namespace gapi::__private {
    
GAPI_IMPL_PRIVATE_DECLARATION(GApiContext)
GAPI_IMPL_PRIVATE_DECLARATION(Surface)
GAPI_IMPL_PRIVATE_DECLARATION(Buffer)
GAPI_IMPL_PRIVATE_DECLARATION(Pipeline)
GAPI_IMPL_PRIVATE_DECLARATION(Shader)
GAPI_IMPL_PRIVATE_DECLARATION(Swapchain)
    
}

#endif // GAPI_FWD_HPP